package com.dukascopy.api;

import java.util.List;

/**
 * Signals, generated by strategy
 * 
 * @author roman.terlan
 */
public interface ISignal {

	enum Type {
		ORDER_BUY,    
		ORDER_SELL, 
		ORDER_CLOSE, 
		ORDER_MODIFY, 
		ORDER_MERGE, 
		ORDER_CANCEL
    }
	
	IOrder getOrder();
	
	List<IOrder> getOldOrders();

	ISignal.Type getType();
}
